TWILIO:
  ACCOUNT_SID: "..."
  AUTH_TOKEN: "..."
  FROM_NUMBER: "..."
  TO_NUMBER: "..."

DATABASE:
  HOST: "localhost"
  PORT: 27017
  DATABASE: "test"

SEARCH_ENGINE:
  MAX_PRICE: 10000
  AREA:
    - 7491 # Portales Norte
    - 7497 # Portales Oriente
    - 7516 # Portales Sur
