TWILIO:
  ACCOUNT_SID: "..."
  AUTH_TOKEN: "..."
  FROM_NUMBER: "..."
  TO_NUMBER: "..."

MONITOR:
  PORT: 8080

REDIS:
  HOST: localhost
  PORT: 6379

SEARCH_ENGINE:
  MAX_PRICE: 10000
  AREA:
    - 7491 # Portales Norte
    - 7497 # Portales Oriente
    - 7516 # Portales Sur
